### ISSUE TITLE
Mac OS support again? or at least a way to run in terminal

### ISSUE THREAD

**Issue by khalilgharbaoui** [takashi1kun/lan-play-GUI#28]

**Comment by takashi1kun** [comment]
Not in the foreseeable future, if Space starts releasing lan play with a mac os distribution i will also start distributing the GUI for mac.

**Comment by khalilgharbaoui** [comment]
sure but its just an elecron gui on top of scripts...

i ran it locally on my mac from your repo it works fine.

adding a build for it is not really a hassel i might just for en do it my self.🤷‍♂️

**Comment by takashi1kun** [comment]
I just assumed that anyone that is capable of building switch-lan-play for mac is capable of building this for mac, as you say is electron, is not hard. 

What i want to avoid is releasing this built for mac while switch lan play is not, i will still unofficially support in the code mac, but i will not be building it or advertising that i support it anymore, because at some point i tried to do it and i got floods of PMs in GBAtemp of neweis that had problems because they had to build SLP by themselves. 

I next versions i plan to have a separate version that is headless and only have a web based gui, this version will not have builded binaries, you just download it and run it yourself with node.

**Comment by khalilgharbaoui** [comment]
@takashi1kun i can help you build those if you want. Im also a software engineer.. and can handle testing builds for you...
i can also do docker... 
as long as your code is open source ill pitch in.
if you are open for that... at least.

**Comment by takashi1kun** [comment]
@khalilgharbaoui  Yeah the dockerized headless version was going oriented more to power users, it will also serve as a cli interface, and would also include standalone commands for example
**lpgui startWebGui** -> this is what most likely would be executed in a docker   

**lpgui startCliGui** -> this start a "GUI" but built in cli   

**lpgui startCommandService** -> this starts a background service to be able to run the commands, startWebGui would also do the same job, but this version starts the service whitout a webserver, the startCliGui does not start this kind of service, as it behaves more like an application than a service 

Next we have commands to interact with this headless version in case someone is even less fan of interfaces and likes his commands  
  
**lpgui ls** -> would list all the servers

**lpgui addserver --name lol --addr whatever.com --port 12345**  

**lpgui ls --public** -> list only public servers, i will host a json with them 

**lpgui ls --private**  -> list only the servers you add on your own

**lpgui connect serverName**  -> would connect to a server, it also accepts the number of the server order

**lpgui disconnect**  

**lpgui startPrivateServer**  

**lpgui config --editor nano** -> will open the config file in nano  

**lpgui findInterfaces**  

**lpgui selectInterface 3**

something like that is what i am thinking, it would server as a headless web server, as a terminal cli interface and would provide commands to interact by commands, all in one, separated from the main GUI, but they would share config/server files estructure so they are interchangeable

The web gui is going to use angular 9 and material design.

**Comment by Ti800** [comment]
Hi,spacemeowx2 is already started releasing the MacOS version of switch-lan-play.Could you support MacOS?This is definitely more convenient than CLI.
